language: java

jdk:
  - oraclejdk7
  - oraclejdk8

notifications:
  email: false

sudo: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/


# prevent travis from running gradle assemble
install: true

script:
  - ./gradlew --configure-on-demand autohash:assemble
  - ./gradlew --configure-on-demand autohash:check
